apiVersion: v1
kind: Endpoints
metadata:
  name: bosh-exporter-service
  namespace: monitoring
subsets:
- addresses:
  - ip: $BOSH-EXPORTER-IP
  ports:
  - name: http
    port: 9190
    protocol: TCP
